name: Daily Commit Check

on:
  schedule:
    # Runs at 930 PM PST every day
    - cron: '30 5 * * *'
  workflow_dispatch: 

jobs:
  check-commits:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check for today's commits
      uses: actions/github-script@v6
      with:
        script: |
          const username = 'tbw875';
          
          // Helper function to convert UTC to PST
          function convertToPST(date) {
            // Use proper timezone conversion
            return new Date(date.toLocaleString("en-US", {timeZone: "America/Los_Angeles"}));
          }
          
          // Get today's date in PST
          const now = convertToPST(new Date());
          const today = now.toISOString().split('T')[0];
          
          let page = 1;
          let commitFound = false;

          function isInCommitWindow(eventDate) {
            const pst = convertToPST(new Date());
            const eventPST = convertToPST(new Date(eventDate));
            
            // Set today's date at 12:01 AM
            const startOfDay = new Date(pst);
            startOfDay.setHours(0, 1, 0, 0);
            
            // Set today's date at 9:30 PM
            const endOfWindow = new Date(pst);
            endOfWindow.setHours(21, 30, 0, 0);
            
            return eventPST >= startOfDay && eventPST <= endOfWindow;
          }
          
          // Check all pages until we find a commit or run out of events
          while (!commitFound) {
            const response = await github.rest.activity.listPublicEventsForUser({
              username: username,
              per_page: 100,  // Maximum allowed
              page: page
            });
            
            // No more events to check
            if (response.data.length === 0) break;
            
            for (const event of response.data) {
              // Check both PushEvents and merged PullRequestEvents
              if (event.type === 'PushEvent' || 
                  (event.type === 'PullRequestEvent' && event.payload?.action === 'closed' && event.payload?.pull_request?.merged)) {
                
                if (isInCommitWindow(event.created_at)) {
                  commitFound = true;
                  break;
                }
              }
            }
            
            page++;
            
            // Avoid checking too many pages
            if (page > 5) break;  // Limit to 500 events
          }
          
          if (!commitFound) {
            // If no commit found, send notification via webhook
            const webhook_url = process.env.WEBHOOK_URL;
            const webhook_secret = process.env.WEBHOOK_SECRET;
            
            await fetch(webhook_url, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'X-Webhook-Secret': webhook_secret
              },
              body: JSON.stringify({
                message: "Don't forget to make your daily commit!"
              })
            });
          }

          
    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
