name: Daily Commit Check

on:
  schedule:
    # Runs at 930 PM PST every day
    - cron: '30 5 * * *'
  workflow_dispatch: 

jobs:
  check-commits:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check for today's commits
      uses: actions/github-script@v6
      with:
        script: |
          const username = 'tbw875';
          
          // Helper function to convert UTC to PST
          function convertToPST(date) {
            return new Date(date.toLocaleString('en-US', {
              timeZone: 'America/Los_Angeles',
              year: 'numeric',
              month: '2-digit',
              day: '2-digit',
              hour: '2-digit',
              minute: '2-digit',
              second: '2-digit',
              hour12: false
            }));
          }
          
          // Get today's date in PST
          const now = convertToPST(new Date());
          const today = now.toISOString().split('T')[0];
          
          let page = 1;
          let commitFound = false;

          function isInCommitWindow(eventDate) {
            // GitHub API returns UTC timestamps
            const eventUTC = new Date(eventDate);
            
            // Convert to PST/PDT
            const pstOptions = { timeZone: 'America/Los_Angeles' };
            const eventPST = new Date(eventUTC.toLocaleString('en-US', pstOptions));
            const nowPST = new Date(new Date().toLocaleString('en-US', pstOptions));
            
            // Get start of day in PST
            const startOfDay = new Date(nowPST);
            startOfDay.setHours(0, 0, 0, 0);
            
            // Get end of window (9:30 PM PST)
            const endOfWindow = new Date(nowPST);
            endOfWindow.setHours(21, 30, 0, 0);
            
            // Debug logging
            console.log('Event UTC:', eventUTC);
            console.log('Event PST:', eventPST);
            console.log('Start of day PST:', startOfDay);
            console.log('End of window PST:', endOfWindow);
            
            return eventPST >= startOfDay && eventPST <= endOfWindow;
          }
          
          // Check all pages until we find a commit or run out of events
          while (!commitFound) {
            const response = await github.rest.activity.listPublicEventsForUser({
              username: username,
              per_page: 100,  // Maximum allowed
              page: page
            });
            
            // No more events to check
            if (response.data.length === 0) break;
            
            for (const event of response.data) {
              console.log('Checking event:', {
                type: event.type,
                created_at: event.created_at,
                repository: event.repo?.name
              });
              
              if (event.type === 'PushEvent' || 
                  (event.type === 'PullRequestEvent' && event.payload?.action === 'closed' && event.payload?.pull_request?.merged)) {
                
                const inWindow = isInCommitWindow(event.created_at);
                console.log('Event in commit window:', inWindow);
                
                if (inWindow) {
                  commitFound = true;
                  console.log('Valid commit found!');
                  break;
                }
              }
            }
            
            page++;
            
            // Avoid checking too many pages
            if (page > 5) break;  // Limit to 500 events
          }
          
          if (!commitFound) {
            // If no commit found, send notification via webhook
            const webhook_url = process.env.WEBHOOK_URL;
            const webhook_secret = process.env.WEBHOOK_SECRET;
            
            await fetch(webhook_url, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'X-Webhook-Secret': webhook_secret
              },
              body: JSON.stringify({
                message: "Don't forget to make your daily commit!"
              })
            });
          }

          
    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
