name: Check Daily Commits

on:
  schedule:
    # Runs at 930 PM PST every day
    - cron: '30 5 * * *'
  workflow_dispatch: 

jobs:
  check-commits:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check for commits
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const username = context.repo.owner;
          let commitFound = false;
          let page = 1;
          
          console.log(`Checking commits for user: ${username}`);
          
          try {
            // Get today's commits across all repositories
            const query = `query($username:String!, $since:GitTimestamp!) {
              user(login: $username) {
                contributionsCollection(from: $since) {
                  commitContributionsByRepository {
                    repository {
                      name
                    }
                    contributions(first: 100) {
                      nodes {
                        occurredAt
                      }
                    }
                  }
                }
              }
            }`;
            
            // Set the start of today in ISO format
            const today = new Date();
            today.setHours(0,0,0,0);
            
            const variables = {
              username: username,
              since: today.toISOString()
            };
            
            console.log('Querying with variables:', variables);
            
            const result = await github.graphql(query, variables);
            console.log('API Response:', JSON.stringify(result, null, 2));
            
            // Check if there are any commits today
            const contributions = result.user.contributionsCollection.commitContributionsByRepository;
            for (const repoContrib of contributions) {
              if (repoContrib.contributions.nodes.length > 0) {
                console.log(`Found commits in ${repoContrib.repository.name}`);
                commitFound = true;
                break;
              }
            }
          } catch (error) {
            console.error('Error fetching commits:', error);
            throw error;
          }
          
          console.log('\n=== Final Result ===');
          console.log('Commit found:', commitFound);
          
          if (!commitFound) {
            // If no commit found, send notification via webhook
            const webhook_url = process.env.WEBHOOK_URL;
            const webhook_secret = process.env.WEBHOOK_SECRET;
            
            await fetch(webhook_url, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'X-Webhook-Secret': webhook_secret
              },
              body: JSON.stringify({
                message: "Don't forget to make your daily commit!"
              })
            });
          }

    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}

permissions:
  contents: read
  actions: read
